# Generated by Django 5.2 on 2025-04-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
